version: '3'
services:
  app:
    container_name: dedupe
    restart: always
    build: .
    ports: 
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: dedupe_mongo
    image: mongo
    ports:
        - '27017:27017'
